### ISSUE TITLE
Downloading wallpaper

### ISSUE THREAD

**Issue by j1mh** [Tech-How/Bing-Wallpaper-for-iOS#2]
Whenever shortcut runs it always loads the same wallpaper. Even if i manually change wallpaper it will reload the same one as before.

Wallpaper is always blurry. I have to manually go in and turn blur off each time.

Also do i want to refresh or save wallpape?
Where does it save the wall papers. When running shortcut some wallpapers appear for me to pick one but i dont know where they are coming from.

The auto run works but just keeps loading same wallpaper.

iphone xr
Ios 16.5

Thanks for any help
James Humphrey

**Comment by Tech-How** [comment]
Hi, thanks for your questions:

- To maintain compatibility with older devices, this shortcut is currently maintained on iOS 15. This means that iOS 16 is automatically applying blur settings to the wallpaper. If you open the shortcut code and scroll down in the shortcut near the bottom you should see a set wallpaper action. If you click the little dropdown arrow on that block you may be able to change additional wallpaper effects. If there isn't a toggle for that (although there should be one) it means that Apple hasn't implemented a way to do this via shortcuts.
- When you click on Change Wallpaper, the shortcut makes a request to [this url](https://bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=ROW), and Bing will return the wallpaper image for that day. It repeats this 7 times, incrementing the `idx=0` value by 1 each time. The wallpapers received from the Bing server are then displayed in a window for you to choose from. These don't get stored on your device unless you manually save them. The Refresh Wallpaper option will download Bing's image for today, whereas Change Wallpaper will return the wallpapers for the previous 7 days. I may consider implementing an auto-save feature in the future.
- If the auto-run runs multiple times during the same day, there will be no new wallpaper because [bing.com](https://www.bing.com) only refreshes the wallpaper every day. If you set the automation to run in the next morning, you should see a new image appear.

-Hope this helps!

**Comment by j1mh** [comment]
Thanks for the quick response. Per your instructions I was able to fix the blur issue.

 Also the auto run is working ok.

Still a little confused on wallpaper info text. Does it only show up when you run it manually? It ran on time this morning but no info text.

Great little shortcut for wallpapers.

Thanks
Jim humphrey


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Tech-How** [comment]
Glad you're enjoying it :)

The little notification text should show when run both manually and automatically. I have seen cases of the shortcut timing out when generating the notification since it generates a preview of the webpage and embeds it there. Do you recall seeing any error messages from shortcuts after the auto run? I removed this function on iPads since it was causing issues but I may have to remove it altogether. If you look underneath the set wallpaper block there is another one that says "If Device Model contains iPhone". When expanded there is an attachment labeled URL. If you remove that, does the notification generate properly?

**Comment by j1mh** [comment]
I was able to play around with shortcut over the weekend. Found out I was getting description text but was buried under my notifications. I cleaned up how and when notifications appear. Everything is working fine. I was expecting the description to appear on the wallpaper instead of a notice. My bad.

Again thanks for the quick response and help.

Jim

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
