### ISSUE TITLE
Automatic refresh

### ISSUE THREAD

**Issue by rudyxxy** [Tech-How/Bing-Wallpaper-for-iOS#5]
Hi,
Can you add an automatic refresh? Notification are interesting, but is so annoying to click on a notification to have a refresh. The automation for my view need to be this, if need manual click is not an automation.
Thanks in advance, in any case great job.

**Comment by Tech-How** [comment]
Hello,
The automation should automatically refresh the wallpaper. Are you sure you told iOS not to ask for confirmation while setting up the automation? There are different settings when setting up the automation like notify, don't notify, ask, etc. Also, check if you have a text or number block containing the number 0 before the "Run shortcut" action in the automation.

Let me know how if you have any trouble

**Comment by rudyxxy** [comment]
Hello,

I'm sure that all Is correct, but in any case the auto refresh doesn't work. This morning the auto rum worked as well, but the background isn't changed. When i have started manually It worked fine.

PS i have tried sometimes to reinstall following instruction step by step, but nothing to do. iOS version 17.2

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Tech-How** [comment]
Hi,
I think what could be happening is that the shortcut tries to run in interactive mode instead of automatic mode. When you run the shortcut directly and no input is passed, it will show a menu with a button to refresh. But if you pass the number 0 to the shortcut as input, it should change automatically.

Here's a video of what my automation looks like (I'm on iOS 15 so it may be different): [https://drive.google.com/file/d/1GVlqjkKtS692BZTVjSaU9fsdHThTglI0/view](https://drive.google.com/file/d/1GVlqjkKtS692BZTVjSaU9fsdHThTglI0/view)

If the automation is correctly configured, does the wallpaper change when you press the play button on the automation to "test" it? Additionally, do you see any notification from the shortcuts app after the automation was triggered, like a success, error, tap to respond/run, or waiting for input?

**Comment by rudyxxy** [comment]
Hi,
All works fine, Apple have changed the shortcuts menù, after a bit of time i have found what you mean.
Very great work...
Let us other interesting automations 🤗

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________
